services:
  app:
    image: mcr.microsoft.com/devcontainers/typescript-node:1-22-bookworm
    tty: true
    stdin_open: true
    volumes:
      - ../:/workspace
      - node_modules:/workspace/node_modules
    ports:
      - 5173:5173

volumes:
  node_modules:
    driver: local
