name: CD

on:
  push:
    branches:
      - master
      - next
    tags:
      - "v*"
    paths-ignore:
      - ".github/**"
      - "**/README*"
  workflow_dispatch:

jobs:
  ci:
    uses: ./.github/workflows/ci.yml

  deploy-docs:
    needs: [ci]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' || github.ref == 'refs/heads/next'
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        uses: actions/cache@v3
        id: cache_dependencies
        with:
          path: node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('yarn.lock') }}
      - run: yarn --frozen-lockfile --non-interactive

      - name: Build v-confirm
        run: yarn run build

      - name: Build docs
        run: yarn run build
        working-directory: ./packages/docs

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./packages/docs/docs

  create-release:
    needs: [ci]
    runs-on: ubuntu-latest
    if: startswith(github.ref, 'refs/tags/v')
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - run: echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Build Release Note
        id: github_release
        uses: mikepenz/release-changelog-builder-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create release tag
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.TAG_NAME }}
          release_name: ${{ env.TAG_NAME }}
          body: ${{steps.github_release.outputs.changelog}}

  publish-npm:
    needs: [create-release]
    runs-on: ubuntu-latest
    if: startswith(github.ref, 'refs/tags/v')
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: "https://registry.npmjs.org"
          scope: "@gn5r"
          always-auth: true
      - name: Install dependencies
        run: yarn --frozen-lockfile --non-interactive
      - name: Publish to npm
        run: bash scripts/release.sh
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
